CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Wpedantic -D_GNU_SOURCE -Werror=all -O2

compare_strings: compare_strings.cpp
	$(CXX) $(CXXFLAGS) compare_strings.cpp -o compare_strings

clean:
	rm -f compare_strings
